name: razorpay_web
description: Flutter plugin for Razorpay SDK. Supports Android, iOS and Web.
version: 1.4.3

homepage: https://github.com/gauravmehta13/razorpay_web
   
environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  eventify: 1.0.1
  package_info_plus: 8.0.2
  universal_platform: 1.1.0
  web: 1.0.0
  js: 0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.4
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:

        android:
            package: com.razorpay.razorpay_flutter
            pluginClass: RazorpayFlutterPlugin
        ios:
            pluginClass: RazorpayFlutterPlugin
        web:
            pluginClass: RazorpayFlutterPlugin
            fileName: razorpay_flutter_web.dart

